# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-08 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_number', models.AutoField(primary_key=True, serialize=False)),
                ('performance_precision', models.FloatField(default=None, null=True)),
                ('answer_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Answer')),
                ('page_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Page')),
                ('predict_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Predict')),
            ],
        ),
    ]
