# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-10 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceEvaluator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='performance_f1',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='performance',
            name='performance_recall',
            field=models.FloatField(default=None, null=True),
        ),
    ]
