# Generated by Django 2.1.5 on 2019-12-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extractor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentextractor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
