# Generated by Django 2.1.5 on 2019-12-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Evaluation', '0002_auto_20191216_1042'),
        ('Core', '0005_auto_20191216_1042'),
        ('Extractor', '0003_auto_20191216_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentextractor',
            name='performance',
            field=models.ManyToManyField(through='Evaluation.PerformanceEvaluationResult', to='Evaluation.PerformanceMetric'),
        ),
        migrations.AlterField(
            model_name='predict',
            name='content_extractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractor', to='Extractor.ContentExtractor'),
        ),
        migrations.AlterField(
            model_name='predict',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test', to='Core.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='predict',
            unique_together={('content_extractor', 'page')},
        ),
    ]
