# Generated by Django 2.1.5 on 2019-12-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Extractor', '0004_auto_20191216_1042'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='predict',
            unique_together={('content_extractor',)},
        ),
    ]
