# Generated by Django 2.1.5 on 2019-12-17 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20191216_1042'),
        ('Extractor', '0005_auto_20191216_1212'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='predict',
            unique_together={('content_extractor', 'page')},
        ),
    ]
