# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-08 04:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answer_number', models.AutoField(primary_key=True, serialize=False)),
                ('answer_scorer', models.TextField(default=None, null=True)),
                ('answer_xpath', models.TextField(default=None, null=True)),
                ('answer_dom', models.TextField(default=None, null=True)),
                ('answer_area_left', models.TextField(default=None, null=True)),
                ('answer_area_right', models.TextField(default=None, null=True)),
                ('answer_area_top', models.TextField(default=None, null=True)),
                ('answer_area_bottom', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_number', models.AutoField(primary_key=True, serialize=False)),
                ('page_url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('site_name', models.TextField()),
                ('site_description', models.TextField()),
                ('menu_xpath', models.TextField(default=None, null=True)),
                ('menu_amount', models.IntegerField(default=None, null=True)),
                ('mht_file', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('predict_number', models.AutoField(primary_key=True, serialize=False)),
                ('predict_method', models.TextField(default=None, null=True)),
                ('predict_xpath', models.TextField(default=None, null=True)),
                ('predict_dom', models.TextField(default=None, null=True)),
                ('predict_area_left', models.TextField(default=None, null=True)),
                ('predict_area_right', models.TextField(default=None, null=True)),
                ('predict_area_top', models.TextField(default=None, null=True)),
                ('predict_area_bottom', models.TextField(default=None, null=True)),
                ('page_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Page')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='page_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Page'),
        ),
    ]
