# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-10-15 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_randomlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_xpath',
        ),
        migrations.RemoveField(
            model_name='predict',
            name='predict_xpath',
        ),
    ]
