# Generated by Django 2.1.3 on 2018-11-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20181015_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_number', models.AutoField(primary_key=True, serialize=False)),
                ('site_name', models.TextField(default=None, null=True)),
                ('site_description', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RandomList',
        ),
    ]
