# Generated by Django 2.1.5 on 2019-02-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20181126_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
