# Generated by Django 2.1.5 on 2019-11-12 06:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('checker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_index', models.PositiveIntegerField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContentExtractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hyu', models.PositiveIntegerField()),
                ('pos_left', models.FloatField()),
                ('pos_right', models.FloatField()),
                ('pos_top', models.FloatField()),
                ('pos_bottom', models.FloatField()),
                ('num_chars', models.IntegerField()),
                ('num_tags', models.IntegerField()),
                ('num_links', models.IntegerField()),
                ('label', models.IntegerField(choices=[(1, 'TEST'), (2, 'TEST'), (3, 'TEST')])),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('mht_file_path', models.FilePathField(null=True, path='./files')),
                ('answer_set_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.AnswerSet')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceEvaluationResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precision', models.FloatField(default=None, null=True)),
                ('recall', models.FloatField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('readable', models.BooleanField(default=False)),
                ('content_extractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.ContentExtractor')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Page')),
            ],
        ),
        migrations.CreateModel(
            name='PredictIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predict_index', models.PositiveIntegerField()),
                ('predict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Predict')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('protocol', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='performanceevaluationresult',
            name='performance_metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.PerformanceMetric'),
        ),
        migrations.AddField(
            model_name='performanceevaluationresult',
            name='predict',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Predict'),
        ),
        migrations.AddField(
            model_name='node',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Page'),
        ),
        migrations.AddField(
            model_name='answer',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Page'),
        ),
        migrations.AlterUniqueTogether(
            name='performanceevaluationresult',
            unique_together={('predict', 'performance_metric')},
        ),
        migrations.AlterUniqueTogether(
            name='node',
            unique_together={('page', 'hyu')},
        ),
    ]
