# Generated by Django 2.1.5 on 2019-11-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSetPage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestSetSite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Site')),
                ('test_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.AnswerSet')),
            ],
        ),
        migrations.AddField(
            model_name='testsetpage',
            name='test_set_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.TestSetSite'),
        ),
    ]
