# Generated by Django 2.1.5 on 2019-12-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceEvaluator', '0002_auto_20191215_0733'),
        ('Core', '0002_auto_20191211_0804'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='performanceevaluationresult',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='performanceevaluationresult',
            name='performance_metric',
        ),
        migrations.RemoveField(
            model_name='performanceevaluationresult',
            name='predict',
        ),
        migrations.AlterUniqueTogether(
            name='predict',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='predict',
            name='content_extractor',
        ),
        migrations.RemoveField(
            model_name='predict',
            name='page',
        ),
        migrations.RemoveField(
            model_name='predictindex',
            name='predict',
        ),
        migrations.DeleteModel(
            name='ContentExtractor',
        ),
        migrations.DeleteModel(
            name='PerformanceEvaluationResult',
        ),
        migrations.DeleteModel(
            name='PerformanceMetric',
        ),
        migrations.DeleteModel(
            name='Predict',
        ),
        migrations.DeleteModel(
            name='PredictIndex',
        ),
    ]
