# Generated by Django 2.1.5 on 2019-11-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='protocol',
            field=models.CharField(default='https', max_length=255),
        ),
    ]
