# Generated by Django 2.1.5 on 2019-12-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20191215_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='indices',
            field=models.ManyToManyField(blank=True, to='Core.Node'),
        ),
    ]
