# Generated by Django 2.1.5 on 2019-11-18 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20191114_0619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='answer_set_id',
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.Site'),
        ),
        migrations.AddField(
            model_name='testsetpage',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.Page'),
            preserve_default=False,
        ),
    ]
