# Generated by Django 2.1.5 on 2019-12-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Extractor', '0003_auto_20191216_0724'),
        ('Core', '0004_answer_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='predicts',
            field=models.ManyToManyField(through='Extractor.Predict', to='Extractor.ContentExtractor'),
        ),
        migrations.AlterField(
            model_name='testset',
            name='sites',
            field=models.ManyToManyField(blank=True, to='Core.Site'),
        ),
    ]
