# Generated by Django 2.1.5 on 2019-11-22 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20191118_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='depth',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='link',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Core.Page'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsetpage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
