# Generated by Django 2.1.5 on 2019-11-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20191122_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='url',
        ),
        migrations.AddField(
            model_name='page',
            name='host',
            field=models.CharField(default='www', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='page',
            name='pathname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='protocol',
            field=models.CharField(default='https', max_length=255),
        ),
    ]
