# Generated by Django 2.1.5 on 2019-11-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_auto_20191128_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
