# Generated by Django 2.1.5 on 2019-11-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_node_node_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='label',
        ),
    ]
