# Generated by Django 2.1.5 on 2019-11-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_remove_node_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeName',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='node',
            old_name='pos_bottom',
            new_name='offset_height',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='pos_right',
            new_name='offset_width',
        ),
    ]
