# Generated by Django 2.1.5 on 2019-11-29 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_auto_20191129_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='pos_left',
            new_name='offset_left',
        ),
        migrations.RenameField(
            model_name='node',
            old_name='pos_top',
            new_name='offset_top',
        ),
    ]
