# Generated by Django 2.1.5 on 2019-12-10 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_number', models.AutoField(primary_key=True, serialize=False)),
                ('performance_metric', models.TextField(default=None, null=True)),
                ('performance_precision', models.FloatField(default=None, null=True)),
                ('performance_recall', models.FloatField(default=None, null=True)),
                ('performance_f1', models.FloatField(default=None, null=True)),
                ('answer_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Answer')),
                ('page_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Page')),
                ('predict_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.Predict')),
            ],
        ),
    ]
