# Generated by Django 2.1.5 on 2019-12-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PerformanceEvaluator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='answer_number',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='predict_number',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
